Check-update: true
Global-settings:
    Money:
        Decimal-places: 2
        Item-drop:
            Enabled: false
            Item-name: "&c${amount}"
            Item-material: GOLD_INGOT
    Farming:
        Disable-spawner-farming: true
        Disable-spawner-egg-farming: true
    General:
        Message-method: CHAT
        Allowed-gamemodes: SURVIVAL
    Limit:
        Reset-time: 24
        Reached-limit-message: true
Configurable-permissions:
    Money-multipliers:
        donator: 1.5
        vip: 2
        elite: 2.5
    Limit-multipliers:
        donator: 1.5
        vip: 2
        elite: 2.5
Hook:
    MobArena:
        Enabled: false
    MineChart:
        Enabled: true
        Graphs:
            MONEY: true